language: python
python:
    - "2.7"
before_install:
    - pip install coveralls
script:
    - py.test
    - coverage run --source=bwtest.py errortest.py test bwtest.py
after_success: coveralls
